Extend documentation of scalar filter types
ChilliCream/graphql-platform pull request #5759
Opened 2023-02-03 14:37 UTC by PascalSenn

Summary of the changes (Less than 80 chars)

- Detail 1
- Detail 2

Closes #bugnumber (in this specific format)

2023-02-03 19:08 UTC, glen-84 requested changes

2023-02-03 19:08 UTC, glen-84 commented on website/src/docs/hotchocolate/v13/fetching-data/filtering.md
> +**Scalars / Operation Input Types**
```suggestion

**Scalars / Operation Input Types**
```

2023-02-03 19:08 UTC, glen-84 commented on website/src/docs/hotchocolate/v13/fetching-data/filtering.md
> +Scalars are mapped to a `FilterInputType` that defines the operation that are possible for this scalar.
```suggestion
Scalars are mapped to a `FilterInputType` that defines the operations that are possible for this scalar.
```

2023-02-03 19:08 UTC, glen-84 commented on website/src/docs/hotchocolate/v13/fetching-data/filtering.md
> +The built in scalars are already mapped to matching filter types.
```suggestion
The built-in scalars are already mapped to matching filter types.
```

2023-02-03 19:08 UTC, glen-84 commented on website/src/docs/hotchocolate/v13/fetching-data/filtering.md
> +```csharp
```suggestion
For comparable value types, you can use the `ComparableOperationFilterInputType<T>` base class.

```csharp
```

2023-02-03 19:08 UTC, glen-84 commented on website/src/docs/hotchocolate/v13/fetching-data/filtering.md
> +```csharp
```suggestion
These types have to be registered on the filter convention:

```csharp
```

2023-02-03 19:08 UTC, glen-84 commented on website/src/docs/hotchocolate/v13/fetching-data/filtering.md
> +  ...;
```suggestion
    .AddGraphQLServer()
    .AddFiltering(x => x.AddDefaults().BindRuntimeType<uint, UnsignedIntOperationFilterInputType>())
    ...;
```

2023-02-05 18:20 UTC, michaelstaib approved these changes

2023-02-05 18:20 UTC, merged