Add "Nodes batch size" section to migrate-from-12-to-13.md
ChilliCream/graphql-platform pull request #5896
Opened 2023-02-28 16:54 UTC by nightroman

One potentially breaking change is yet missing in the migration document.
The new section was discussed with @tobias-tengler on [Slack](https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1677600704915189)

2023-02-28 16:58 UTC, tobias-tengler approved these changes

2023-02-28 16:58 UTC, tobias-tengler requested changes

2023-02-28 17:00 UTC, tobias-tengler approved these changes

2023-03-02 00:09 UTC, michaelstaib commented
Thanks for your contribution.

2023-03-02 00:10 UTC, merged