Fix broken links
ChilliCream/graphql-platform pull request #6067
Opened 2023-04-18 15:54 UTC by wilmerferreira

This contains fixes for broken links in docs

2023-04-18 15:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChilliCream/graphql-platform?pullRequest=6067) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChilliCream/graphql-platform?pullRequest=6067) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChilliCream/graphql-platform?pullRequest=6067) it.</sub>

2023-04-18 16:14 UTC, tobias-tengler requested changes
Thanks for fixing the links, but the `<PackageInstallation ...`s you marked as code are actual React components being displayed on the Website. Marking them as code would be wrong. I understand that this is suboptimal for people viewing the raw markdown files. Do you know of any mechanism to fallback to text for raw markdown?

2023-04-18 16:39 UTC, wilmerferreira commented
Removed changes around React components

2023-04-19 18:23 UTC, tobias-tengler approved these changes

2023-04-22 04:17 UTC, merged