Fixed NullReferenceException in OperationComplexityMiddleware (#5278)
ChilliCream/graphql-platform pull request #6099
Opened 2023-04-28 19:32 UTC by marcioscpinheiro

- Fixes the operation complexity cache key
- Change the comparison to the SyntaxComparison

Closes #5278

2023-04-28 19:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChilliCream/graphql-platform?pullRequest=6099) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChilliCream/graphql-platform?pullRequest=6099) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChilliCream/graphql-platform?pullRequest=6099) it.</sub>

2023-05-01 07:25 UTC, michaelstaib commented
The fix introduces a new bug as the cache id is for the request but we need one for the operation.

2023-05-01 07:27 UTC, michaelstaib commented
Actually, it was correct as it was and this introduces a bug.

2023-05-01 07:29 UTC, michaelstaib commented on src/HotChocolate/Core/src/Execution/Pipeline/OperationComplexityMiddleware.cs
> +                if (analyzer.OperationDefinitionNode.Equals(operationDefinition, SyntaxComparison.Syntax))
A reference check should be sufficient here as we are dealing with the same document. Why would you need to compare the syntax tree?

2023-05-01 07:30 UTC, michaelstaib commented on src/HotChocolate/Core/src/Execution/Pipeline/OperationComplexityMiddleware.cs
> +                    _cache.TryAddAnalyzer(
This is incorrect, we create all analyzers here not just for the current operation. This should in the very least have a `break`. What is your reasoning here?

2023-05-01 07:31 UTC, michaelstaib requested changes
This PR introduces issues, see my comments.

2023-05-01 07:33 UTC, michaelstaib commented
Also, can you add a test that shows how to create the NullRefException?

2023-05-01 08:09 UTC, michaelstaib commented
I have a test of issue one .... in the invoke method the cache ID is wrong...

2023-05-01 08:53 UTC, michaelstaib commented
I have explored the issue more and there is more to it ... I am closing this issue in favor of another PR I have open that will tackle the caching issue more broadly.

2023-05-01 09:07 UTC, michaelstaib commented
#6100

2023-05-01 09:12 UTC, merged

2023-05-01 09:13 UTC, michaelstaib commented
We will still give you credits for the fix, thats why I merged you initial attempt.

2023-05-01 11:22 UTC, marcioscpinheiro commented
Thanks Michael, really appreciate your quick response.