Support ID list deserialization with custom Ids
ChilliCream/graphql-platform pull request #6918
Opened 2024-02-18 18:36 UTC by faddiv

Hi,
We ran into this problem when we tried to use plural custom id-s.

- CreateListFactory for custom types creates a string list instead of a custom type list. From this, the type converter can pick up it and create the correct type.

I used one of the recommendations from [this PR](https://github.com/ChilliCream/graphql-platform/pull/5160) to solve the issue.

Closes #5114

2024-02-18 18:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChilliCream/graphql-platform?pullRequest=6918) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChilliCream/graphql-platform?pullRequest=6918) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChilliCream/graphql-platform?pullRequest=6918) it.</sub>

2024-02-19 13:24 UTC, michaelstaib requested changes
Let me check why the type conversion does not work with typed lists ... I think the change should not be needed.

2024-02-19 14:24 UTC, faddiv commented
> Let me check why the type conversion does not work with typed lists ... I think the change should not be needed.

It doesn't work, because the createList creates a list with concrete type. In this case: new List<CustomId>()
but the id serializer serializes the CustomId with (d)efault type; when it deserializes it, string type is used. This results in error.
The type conversion happens after the ID deserialization, so that can't help. The old PR tried to bring in the conversion, but that would change the public API.

2024-02-24 19:54 UTC, faddiv commented
Hi Michael,
If you have time, please consider whether my implementation helps improve HotChocolate.
As far as I can tell, CustomId parsing in `List<>` is only possible this way since the conversion happens later.
I improved my solution. Now it works even if the serialized ID is not the default type.
I investigated the serializing side also, and there the non-default serialization only happens if a custom resolver is created, which transforms the value to one of the basic types.

2024-04-06 19:40 UTC, closed without merging

2024-04-06 20:51 UTC, faddiv commented
Hi Michael,
As I see this is solved in this PR: https://github.com/ChilliCream/graphql-platform/pull/7026 so I closed.